### PR TITLE
v1.6.0rc

### PR DESCRIPTION
**Pull request by operand**
# Summary of Changes

## `Space` types now support mixed threading/multiprocessing for agents

[Version 1.4]() introduced multiprocessing but did not allow threading and multiprocessing based agents to be used together. Additionally the API prevented some use cases that were previously possible, due to not allowing direct access to agents from the main thread.

In 1.6.0, all agents are now `add`'ed using `multiprocessing` based subprocesses by default. Agents added this way may not be directly accessed, similar to 1.4.

With 1.6.0 you now have the option to run agents in the "foreground" using `Space.add_foreground`. When adding an agent this way, an instance of the agent is returned in the current thread. For example:

```py
my_agent = my_space.add_foreground(MyAgent, "my_agent")
```

The tradeoff for adding an agent in the foreground is performance. Due to the python GIL, agents running in the foreground may not be fully parallel with other agents, and may block the main thread.

It's recommended to use `Space.add_foreground` only when needed.

## `MultiprocessSpace` and `ThreadSpace` classes replaced with `LocalSpace`

Since all `Space` types now support mixed threading/multiprocessing, `LocalSpace` combines these older types into a single class for in-application communication.

## Context manager support and `Space.destroy` method added

These two additions allow for improved resource management. Creating and cleaning up a `Space` can now be done using the context manager syntax:

```py
with AMQPSpace() as space:
    space.add(Host, "Host")
    ...
```

This form will automatically clean up Space related resources upon exit of the `with` block.

Direct control of cleanup is also possible using the `Space.destroy` method.

```py
space = AMQPSpace()
space.add(Host, "Host")
...
space.destroy()
```

## `Agent.respond_with` and `Agent.raise_with` methods added

These methods are intended for use with `Agent.request` and the response callbacks: `Agent.handle_action_value` and `Agent.handle_action_error`.

Automatic response behavior has changed from v1.5. Actions will no longer automatically return their return value to the sender.

To explicitly return a value to the sender associated with the current message, use `Agent.respond_with`. For example:

```py
@action
def ping(self):
    self.respond_with("pong")
```

The above will invoke the `handle_action_value` callback on the sender with the value `"pong"`, or return the value `"pong"` directly when used with the `request` method.

Similarly you may return an error with:
```py
@action
def ping(self):
    self.raise_with(Exception("oops"))
```

Actions that raise exceptions will automatically call the `raise_with` method.

Note that `respond_with` and `raise_with` may be called multiple times in a single action. Each call will invoke the appropriate callback on the sender.

When using `request` the first call to `respond_with` will return the value to the calling thread. Subsequent responses will invoke the `handle_action_value` callback.

## Performance Improvements

All busy waiting has been replaced with event based processing. The test suite completes about 80% faster than in 1.5 and CPU overhead should now be minimized. (benchmarking needed)

## `Agent.__init__` signature updated

The Agent constructor has been reverted to its older signature which does not include a `Queue` parameter. Make sure to update your classes.
```py
def __init__(self, id: str, receive_own_broadcasts: bool = True):
```

### CODE REVIEW

**Comment by operand** [comment]
@wwj718 @hidaris

1.6.0 is ready for review if you guys want to try it out ahead of release. I've posted the summary of changes above which will become the release notes for the update.

The demo app has been updated. Note that there's just two demos now: `local` and `amqp`.

I still have to work through updating documentation and do some more testing. So this will likely not be released for at least another day.

I appreciate if you guys have the time to try it out! Let me know if you run into any issues or have any feedback on these changes.

**Comment by wwj718** [comment]
I love all these updates, especially respond_with!
I'll be testing it today and provide feedback here if needed.

**Comment by operand** [comment]
I'm aware that there's a heartbeat related connection issue with the `AMQPSpace`. Working on it.

**Comment by hidaris** [comment]
I just finished reading the PR content for version 1.6, and I'm quite satisfied with the goals and implementation of this milestone. 👍

**Comment by wwj718** [comment]
I have two doubts:

1. [self._direct_exchange = kombu.Exchange(self.exchange_name, 'direct', durable=True)](https://github.com/operand/agency/blob/foreground/agency/spaces/amqp_space.py#L74), Can _direct_exchange and _broadcast_exchange use topic exchange? My current favorite way to debug is [receive all the logs](https://github.com/operand/agency/blob/main/scripts/receive_logs_topic.py#L8), It relies on topic support for wildcards.

2. [producer.publish(...](https://github.com/operand/agency/blob/foreground/agency/spaces/amqp_space.py#L153)  and [self._received_queue.put(body)](https://github.com/operand/agency/blob/foreground/agency/spaces/amqp_space.py#L67)  does not clearly indicate the encoding and decoding method of the message(Previous versions used json). It seems to be better to handle encoding and decoding explicitly to facilitate interoperability with agents implemented by other amqp clients. This current modification will break other clients' json-encoded messages.

**Comment by operand** [comment]
1. I'm going to say no for now on this one. The implementation is directly what it needs to be for point to point and broadcast. We can talk about making this change though, but I don't want to hold up this release.  Let's maybe take it to an issue.
2. Nice catch! I remember changing that and I didn't come back to fix it...

Did you want more time for review? I'm getting close to releasing.

**Comment by wwj718** [comment]
@operand I don't need more time to review, we can release the current version, and I will raise other questions in the issue.

**Pull request merged**
