### PR TITLE
improve request semantics (1.5.0rc)

### PR DESCRIPTION
**Pull request by operand**
This PR addresses the request related issues brought up [here](https://github.com/operand/agency/issues/142) regarding the use of multiple "meta" id's and the semantics of automatic responses to messages.

Since this includes breaking changes, this will likely become the 1.5 release.

Summary:

- All messages now populate the `meta.id` field with a UUID by default. Agents may set their own custom `meta.id` upon sending to overwrite the generated ID.

  In addition, `Agent.send()` now returns the `meta.id` of the sent message.  This way you may store the generated ID for your own purposes.

- Removed the use of `meta.response_id` and `meta.request_id`. These have been replaced by `meta.parent_id`. I think the term "parent" is clearer. This choice is inspired by the [Jupyter messaging docs](https://jupyter-client.readthedocs.io/en/stable/messaging.html).
  
  To be clear, `meta.parent_id` if set, refers to the `meta.id` of the original message which the current message is responding to.

  To illustrate, the following would be typical meta fields in a send/response pair:
  ```py
  # send
  {
    "meta": {
      "id": "123", # the message ID here
    },
    ...
  }
  # response
  {
    "meta": {
      "id": "456", # response has its own unique meta.id
      "parent_id": "123", # refers to the prior message
    },
    ...
  }
  ```

- All messages will now result in a `[response]` message like the above, returning the return value or error result from the message's action.

  One might want to filter these messages from view in a user interface. The demo Gradio app has been updated to demonstrate this. See the `_should_render()` and `get_chatbot_message()` methods for an example.

- `Agent.original_message()` has been renamed to `Agent.parent_message()`.  Additionally `parent_message()` takes a message as a parameter, allowing you to traverse a chain of messages in reverse.

- Internally renamed `Agent._pending_responses` to `Agent._pending_requests` which I think is clearer.

- The logger has been updated to provide colorization of output for easier reading. You may change the default "monokai" pygments style used for object output, by setting the `LOG_PYGMENTS_STYLE` environment variable.

- Log "warning" messages for unimplemented `handle_action_value` and `handle_action_error` methods have been updated to only print once per session, in order to reduce logging noise in the default setting.

- Tests and documentation updated.

### CODE REVIEW

**Comment by operand** [comment]
@wwj718 I'm almost finished with this PR to improve the request behavior. I just have to update the documentation at this point. If you have a chance I appreciate you taking a look. This will be the 1.5 release. I'll wait a day or so before merging to allow for feedback. Thanks!

**Comment by wwj718** [comment]
I think the current refactoring is excellent and solves my doubt in https://github.com/operand/agency/issues/142

**Review by wwj718 — COMMENTED** [review]
it is great!

**Comment by operand** [comment]
Thanks @wwj718! I'll likely be finishing this up and merging 1.5 shortly.

**Pull request merged**
